# Generated by Django 6.0.4 on 2026-05-02 21:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_horario_matricula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nombre'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Curso Activo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='categoria',
            field=models.CharField(blank=True, choices=[('matematicas', 'Matemáticas'), ('ciencias', 'Ciencias'), ('humanidades', 'Humanidades'), ('tecnologia', 'Tecnología'), ('idiomas', 'Idiomas'), ('artes', 'Artes'), ('deportes', 'Deportes')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7, verbose_name='Color Identificador'),
        ),
        migrations.AddField(
            model_name='curso',
            name='creditos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Créditos'),
        ),
        migrations.AddField(
            model_name='curso',
            name='cupo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cupo Máximo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.CharField(blank=True, choices=[('bimestral', 'Bimestral (2 meses)'), ('trimestral', 'Trimestral (3 meses)'), ('semestral', 'Semestral (6 meses)'), ('anual', 'Anual (12 meses)')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='icono',
            field=models.CharField(default='book', max_length=50, verbose_name='Icono FontAwesome'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nivel',
            field=models.CharField(blank=True, choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='core.profesor'),
        ),
    ]
